# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Python Checks

on: pull_request

jobs:
  python-checks:
    runs-on: ubuntu-latest
    env:
      PATH: ${{ github.workspace }}/go/bin:${{ github.workspace }}/.cargo/bin:${{ github.workspace }}/.local/share/pnpm:${{ github.workspace }}/.local/bin:/usr/local/bin:/usr/bin:/bin
    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Pre-requisites
        run: bin/setup -a ci

      - name: Install uv and setup Python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Format check
        run: uv run --directory py ruff format --check .

      - name: Lint with ruff
        run: uv run --directory py ruff check .

      - name: Check licenses
        run: ./bin/check_license

      - name: Run tests
        run: ./py/bin/run_python_tests

      - name: Build documentation
        run: uv run --directory py mkdocs build --strict

      - name: Build distributions
        run: ./py/bin/build_dists
